services:
  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    ports:
      - "9090:9090"   # the default port used by Prometheus
    volumes:
      - ${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yml # mount Prometheus config file

  grafana:
    image: grafana/grafana:latest
    network_mode: host
    depends_on:
      - prometheus
    ports:
      - "3000:3000" # the default port used by Grafana