name: Build Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: 1-gpu-runner
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 改为与其他 workflow 一致的 Python 版本

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e "python[all]"
          pip install -r docs/requirements.txt
          pip install nbconvert jupyter_client ipykernel ipywidgets matplotlib
          pip install transformers==4.45.2
          pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.4/ --force-reinstall

      - name: Setup Jupyter Kernel
        run: |
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: Execute notebooks
        env:
          HF_HOME: /hf_home
          SGLANG_IS_IN_CI: true
          CUDA_VISIBLE_DEVICES: 0  # 参考 setup_github_runner.md 中的环境变量
        run: |
          cd docs/en
          for nb in *.ipynb; do
            if [ -f "$nb" ]; then
              echo "Executing $nb"
              jupyter nbconvert --to notebook --execute --inplace "$nb" \
                --ExecutePreprocessor.timeout=600 \
                --ExecutePreprocessor.kernel_name=python3
            fi
          done

      - name: Build documentation
        run: |
          cd docs/en
          make html

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/en/_build/html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}  # 需要设置 deploy key
          publish_dir: docs/en/_build/html
          force_orphan: true
          full_commit_message: 'docs: update documentation'


# Python 版本改为 3.9，与其他 workflow 保持一致
# 使用 deploy_key 而不是 github_token，这样更安全
# 添加了 CUDA_VISIBLE_DEVICES 环境变量
# 修改了文档构建路径为 docs/en
# 添加了 force_orphan 和 commit message 配置
# 你需要在 GitHub 仓库设置中：
# 生成一个新的 SSH key pair
# 在仓库的 Settings -> Deploy Keys 中添加公钥，并勾选 "Allow write access"
# 在仓库的 Settings -> Secrets -> Actions 中添加名为 ACTIONS_DEPLOY_KEY 的私钥