name: Release PyPI
on:
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'sgl-project/sglang'
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to pypi
        run: |
          cd python
          cp ../README.md ../LICENSE .
          pip install build
          python3 -m build
          pip install twine
          python3 -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}

      - name: Get package version
        id: get_version
        run: |
          VERSION=$(grep -o '__version__ = "[^"]*"' python/sglang/version.py | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Calculate SHA-256 hashes locally
        run: |
          python scripts/release/calculate_local_hashes.py sglang --version ${{ steps.get_version.outputs.version }} --dist-dir python/dist --output hash.txt

      - name: Upload hash.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sglang-hashes
          path: hash.txt
