name: Release Docker Images
on:
  push:
    branches:
      - main
    paths:
      - "python/sglang/version.py"
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'sgl-project/sglang'
    runs-on: ubuntu-latest
    environment: 'prod'
    strategy:
      matrix:
        vendor_version: ['11.8.0', '12.1.1', '12.4.1', '6.2.0']
        build_type: ['all', 'srt']
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          version=$(cat python/sglang/version.py | cut -d'"' -f2)

          if [ "${{ matrix.vendor_version }}" = "11.8.0" ]; then
            ven_tag="cu118"
          elif [ "${{ matrix.vendor_version }}" = "12.1.1" ]; then
            ven_tag="cu121"
          elif [ "${{ matrix.vendor_version }}" = "12.4.1" ]; then
            ven_tag="cu124"
          elif [ "${{ matrix.vendor_version }}" = "6.2.0" ]; then
            ven_tag="rocm620"
          else
            echo "Unsupported CUDA or ROCm version"
            exit 1
          fi

          tag=v${version}-${ven_tag}

          if [ "${{ matrix.build_type }}" = "all" ]; then
            tag_suffix=""
          elif [ "${{ matrix.build_type }}" = "srt" ]; then
            tag_suffix="-srt"
          else
            echo "Unsupported build type"
            exit 1
          fi

          if [ "${{ matrix.vendor_version }}" = "6.2.0" ]; then
            docker build . -f docker/Dockerfile.rocm --build-arg BUILD_TYPE=${{ matrix.build_type }} -t lmsysorg/sglang:${tag}${tag_suffix} --no-cache
          else
            docker build . -f docker/Dockerfile --build-arg CUDA_VERSION=${{ matrix.vendor_version }} --build-arg BUILD_TYPE=${{ matrix.build_type }} -t lmsysorg/sglang:${tag}${tag_suffix} --no-cache
          fi
          docker push lmsysorg/sglang:${tag}${tag_suffix}

          if [ "${{ matrix.vendor_version }}" = "12.1.1" ]; then
            docker tag lmsysorg/sglang:${tag}${tag_suffix} lmsysorg/sglang:latest${tag_suffix}
            docker push lmsysorg/sglang:latest${tag_suffix}
          fi
